package es.ifp.gestordescargas;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Santiago Faci
 */
public class PanelDescarga extends javax.swing.JPanel {

    private String url;
    private JPanel panelDescargas;
    private TareaDescarga tareaDescarga;
    
    public PanelDescarga(String url, JPanel panelDescargas) {
        this.url = url;
        this.panelDescargas = panelDescargas;
        initComponents();
        
        iniciarDescarga();
    }
    
    private void iniciarDescarga() {
        tareaDescarga = new TareaDescarga(url);
        tareaDescarga.addPropertyChangeListener(event -> {
            if (event.getPropertyName().equals("progress")) {
                pbProgreso.setValue((Integer) event.getNewValue());
            }
        });
        tareaDescarga.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbProgreso = new javax.swing.JProgressBar();
        lbDescarga = new javax.swing.JLabel();
        btPausa = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();

        pbProgreso.setPreferredSize(new java.awt.Dimension(300, 20));
        add(pbProgreso);

        lbDescarga.setText("Descarga");
        add(lbDescarga);

        btPausa.setText("[]");
        btPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPausaActionPerformed(evt);
            }
        });
        add(btPausa);

        btEliminar.setText("X");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });
        add(btEliminar);
    }// </editor-fold>//GEN-END:initComponents

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Estás seguro?", "Eliminar Descarga",
                JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION)
            return;
        
        tareaDescarga.cancelar();
        
        panelDescargas.remove(this);
        panelDescargas.revalidate();
        panelDescargas.repaint();
    }//GEN-LAST:event_btEliminarActionPerformed

    private void btPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPausaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPausaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btPausa;
    private javax.swing.JLabel lbDescarga;
    private javax.swing.JProgressBar pbProgreso;
    // End of variables declaration//GEN-END:variables
}
